---
#
# Based on:
# * https://github.com/elixir-mint/castore/tree/v0.1.11/.github/workflows
#
name: Check for updates to hardcoded CAs
on:
  schedule:
    - cron: '23 10 * * 1-5'
  workflow_dispatch:
jobs:
  outdated:
    name: Check for updates to hardcoded CAs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-elixir@v1
        with:
          ref: 'master'
          otp-version: 27.2
          rebar3-version: 3.24
      - run: |
          .github/workflows/hardcoded-authorities-updater.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
